-- MySQL Script generated by MySQL Workbench
-- Sun Feb  7 13:26:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_movies2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_movies2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_movies2` DEFAULT CHARACTER SET utf8 ;
USE `my_movies2` ;

-- -----------------------------------------------------
-- Table `my_movies2`.`Actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_movies2`.`Actors` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `actorName` VARCHAR(100) NOT NULL,
  `credits` INT NULL,
  `linkIMDB` VARCHAR(150) NULL,
  `registerDate` DATE NULL,
  `lastUpdate` DATE NULL,
  PRIMARY KEY (`idActor`))
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `my_movies2`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_movies2`.`Genres` (
  `idGenre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NULL,
  `registerDate` DATE NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `my_movies2`.`Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_movies2`.`Movies` (
  `idMovie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `originalTitle` VARCHAR(100) NULL,
  `year` VARCHAR(4) NULL,
  `linkIMDB` VARCHAR(200) NULL,
  `registerDate` DATE NULL,
  `lastUpdate` DATE NULL,
  `idGenre` INT NOT NULL,
  PRIMARY KEY (`idMovie`),
  INDEX `fk_Movies_Genres1_idx` (`idGenre` ASC) VISIBLE,
  CONSTRAINT `fk_Movies_Genres1`
    FOREIGN KEY (`idGenre`)
    REFERENCES `my_movies2`.`Genres` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_movies2`.`Actors_has_Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_movies2`.`Actors_has_Movies` (
  `idActor` INT NOT NULL,
  `idMovie` INT NOT NULL,
  PRIMARY KEY (`idActor`, `idMovie`),
  INDEX `fk_Actors_has_Movies_Movies1_idx` (`idMovie` ASC) VISIBLE,
  INDEX `fk_Actors_has_Movies_Actors_idx` (`idActor` ASC) VISIBLE,
  CONSTRAINT `fk_Actors_has_Movies_Actors`
    FOREIGN KEY (`idActor`)
    REFERENCES `my_movies2`.`Actors` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actors_has_Movies_Movies1`
    FOREIGN KEY (`idMovie`)
    REFERENCES `my_movies2`.`Movies` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
